title = "Information About A UW Research Study"
subtitle = "Donate your “generative AI” chat transcripts to science!"

header_1 = "What is this study about?"

text_1 = "You are being asked to participate in a research study about the linguistic characteristics of conversations between human users and “generative AI” chatbots. It is up to you to decide whether you want to participate. If you decide to enroll, you can stop participation at any time."

text_2 = "We are asking you to be in the study if you are a current user of “generative AI” chatbots, including ChatGPT, Bard, or Bing Chat. Please do not participate in the study if you are working or studying in related fields, including natural language processing, computational linguistics, machine learning, artificial intelligence, or computer science."

text_3 = "Please read this form and ask any questions you may have before agreeing to be in this study. Only participate in this study if you are 18 or older and living in the US."

header_2 = "What will you be asked to do?"

text_4 = "If you agree to be in this study, we will ask you to fill in a short demographic survey, then participate in a chat with a “generative AI” chatbot. You may converse with the chatbot for any length of time and on any subject. At any time, you may press a “Submit” button to send your chat transcript to the researcher. You always have the option not to submit a chat transcript. You may repeat this process up to 20 times. "

text_5 = "We are especially interested in learning more about how people use chatbots in the context of their everyday lives! Please use this chatbot whenever you typically would throughout the course of your day."

header_3 = "What are the risks of participating in this study?"

text_6 = "The text generated by “generative AI” chatbots is unpredictable. Interacting with this chatbot carries risks, including:"

bullet_1 = "Misinformation: messages from this chatbot may contain misleading, false, or harmful information. "

bullet_2 = "Emotional distress: messages from this chatbot may be inappropriate for your situation or may be upsetting."

text_7 = "Always be skeptical when interacting with a “generative AI” chatbot. Do not act on text generated by these chatbots. "

header_4 = "What will happen to the information you provide? "

text_8 = "Your demographic survey and chat transcripts will be anonymous. We will store them securely and separate from each other, with no identifying link between them."

text_9 = "Do not include personal, private, or identifying information in your chat messages. This study uses a GPT model from OpenAI. When you chat with the chatbot, your chat messages will be sent to OpenAI."

text_10 = "Portions of your chat transcripts may also be made public, either through inclusion in the researcher’s M.S. thesis, or when depositing the dataset in an archive such as University of Washington ResearchWorks. We will make every effort to remove identifying information before making any part of the data public."

header_5 = "What can you do if you want more information?"

text_11 = "Talk to the study team. Elizabeth Okada is the lead researcher at the University of Washington for this study and can be contacted at esokada@uw.edu."

text_12 = "Talk to someone else. If you want to talk with someone who is not part of the study team about the study, your rights as a research subject, or to report problems or complaints about the study, contact the UW Human Subjects Division at hsdinfo@uw.edu or 206-543-0098."
